# Generated by Django 2.2.5 on 2021-03-15 09:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(help_text='Write your answer here...', max_length=2000)),
                ('date_created', models.DateField(default=datetime.datetime(2021, 3, 15, 9, 49, 10, 775926, tzinfo=utc), null=True)),
                ('date_updated', models.DateField(default=datetime.datetime(2021, 3, 15, 9, 49, 10, 775939, tzinfo=utc), null=True)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('date_created', models.DateField(default=datetime.datetime(2021, 3, 15, 9, 49, 10, 775199, tzinfo=utc), null=True)),
                ('credits', models.IntegerField(default=0)),
                ('year', models.DateField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.TextField(help_text='Enter the question title', max_length=300)),
                ('question_text', models.TextField(help_text='Your question in brief', max_length=1000)),
                ('date_created', models.DateField(default=datetime.datetime(2021, 3, 15, 9, 49, 10, 776401, tzinfo=utc), null=True)),
                ('date_updated', models.DateField(default=datetime.datetime(2021, 3, 15, 9, 49, 10, 776413, tzinfo=utc), null=True)),
                ('time_created', models.TimeField(default=datetime.datetime(2021, 3, 15, 9, 49, 10, 776420, tzinfo=utc), null=True)),
                ('slug', models.SlugField(blank=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='konnectapp.Author')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(help_text='Enter your comment...', max_length=1000)),
                ('date_created', models.DateField(default=datetime.datetime(2021, 3, 15, 9, 49, 10, 775529, tzinfo=utc))),
                ('date_updated', models.DateField(default=datetime.datetime(2021, 3, 15, 9, 49, 10, 775543, tzinfo=utc))),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='konnectapp.Answer')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='konnectapp.Author')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='konnectapp.Author'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='konnectapp.Question'),
        ),
    ]
