# Generated by Django 2.2.5 on 2021-03-15 09:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('konnectapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 53, 38, 897350, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 53, 38, 897361, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 53, 38, 896565, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='year',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 53, 38, 896616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 53, 38, 896930, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 53, 38, 896943, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 53, 38, 897742, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 53, 38, 897755, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2021, 3, 15, 9, 53, 38, 897762, tzinfo=utc), null=True),
        ),
    ]
