# Generated by Django 2.2.5 on 2021-03-15 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('konnectapp', '0002_auto_20210315_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 54, 14, 784447, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 54, 14, 784459, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 54, 14, 783694, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='year',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 54, 14, 783733, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 54, 14, 784062, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 54, 14, 784074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 54, 14, 784902, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date_updated',
            field=models.DateField(default=datetime.datetime(2021, 3, 15, 9, 54, 14, 784915, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2021, 3, 15, 9, 54, 14, 784922, tzinfo=utc), null=True),
        ),
    ]
